version:
checks:
  argument-count:
    enabled: true
    config:
      threshold: 8
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-complexity:
    enabled: false
    config:
      threshold:
  method-count:
    enabled: true
    config:
      threshold: 25
  method-lines:
    enabled: true
    config:
      threshold: 30
  nested-control-flow:
    enabled: true
    config:
      threshold: 6
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: false
    config:
      threshold:
  identical-code:
    enabled: false
    config:
      threshold:

exclude_patterns:
- "test"
- "test/" 
- "tests/"
- "spec/"
- "config/"
- "db/"
- "dist/"
- "features/"
- "venv/"
- "**/node_modules/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "**/*.js"
- "**/*.js.map"
- "**/*.json"
- "**/*.jsx"
- "**/*.ts"
- "**/*.tsx"

